### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by mediacobbler** [vojtajina/sublime-OpenRelated#1] opened 2012-03-09 14:48 UTC
im on a windows machine so super+t (windows button +t) should open the related files but its not working. i'm not sure what to highlight... do you select src="file.js" or just file.js? or can you select all and it opens up all related files?  no matter what i do, i always get the message : " Cannot find related file! " 

-thanks

**Comment by vojtajina** [comment] 2012-03-09 17:41
Hey, it's not based on context (selected text), you have to configure relations between files.
There are couple of default patterns, but they obviously don't work for your project layout.

An example layout of a project:
- src/some/file.js
- src/another.js
- src/one.js
- test/some/file.test.js
- test/another.test.js
- test/one.test.js

Now, if you put into your settings (per project / global)

``` javascript
// Some.sublime-project
{
    "build_systems": [],
    "folders": [],
    "settings":
    {
        // THIS IS IMPORTANT
        "open_related_patterns": [
          ["*/src/*.js", "*/test/*.test.js"]
        ]
    }
}
```

**Comment by mediacobbler** [comment] 2012-03-12 22:45
// Some.sublime-project
{
    "build_systems": [],  // how does it know the difference between projects?
    "folders": [],
    "settings":
    {
        // THIS IS IMPORTANT
        "open_related_patterns": [
          ["_/src/_.js", "_/test/_.test.js"]
        ]
    }
}

// another.sublime-project
{
    "build_systems": [something in here? ],  // how does it know the difference between projects?
    "folders": [ something in here? ],
    "settings":
    {
        // THIS IS IMPORTANT
        "open_related_patterns": [
          ["_/src/js/_.js", "_/test/js/_.test.js"]
        ]
    }
}

**Comment by vojtajina** [comment] 2012-03-13 00:19
`*.sublime-project` file is project definition, so have this file per project.

Of course you can specify "open_related_patterns" in your global preferences (for all projects). Just press `CMD+,` if you are on Mac.

Anyway, I don't think this is related to this plugin.

**Comment by nathanielx** [comment] 2012-03-14 23:35
I am also unable to get this plugin to work. I've tried putting the settings in the global Preferences.sublime-settings and in the project file (project.sublime-settings in this case), and neither way works. I'm not completely new to Sublime, but it's possible I may have mis-configured the plugin so I've included the details below:

my setup:
Sublime build 2181
Open Related version: 2012.02.27.04.02.52

my project file structure:
project/functions/source.pm
project/standard/css/source.css
project/standard/js/source.js
project/standard/template/source.tp

"super+t" is already assigned to a default function on Win 7, so reassigned the key to "super+s" by adding the following line to my Default(windows).sublime-keymap:

<pre>
[
   { "keys": ["super+s"], "command": "open_related" }
]
</pre>

I try this by opening 'source.pm' and using the key combo. I get the status message "cannot find related file !", so the key combo appears to be working, but the plugin hasn't found anything because it still needs configuring. So next I edited the project file to look like the following:

<pre>
{
   "folders":
   [
      { "path": "/C/Users/fooey/Code/project/" }
   ],
   "settings":
   {
      "open_related_patterns":
         [
           ["*/functions/*.pm", "*/standard/css/*.css"      ],
           ["*/functions/*.pm", "*/standard/js/*.js"        ],
           ["*/functions/*.pm", "*/standard/templates/*.txt"]
         ]
   }
}
</pre>


And I'm still getting the status message of "cannot find related file !" Have I missed something? From the Readme and the included examples above, this appears correct.

**Comment by vojtajina** [comment] 2012-03-15 02:21
Hmm, that's weird, your configuration seems to be correct.
I've just tried to create your file structure and copied your config and it works for me.
Are you saying you are on Windows ?

If you are ok, to do a little bit of debugging, can you try this ?
Open /yourpathto sublime/Packages/Open Related/open_related.py
add this line after line #10
`print "LOADED" + str(len(view.settings().get('open_related_patterns', [])))`

Save the change, go to your project, press the combo and check out console (`CTRL+\``), how many patterns are loaded ? what is the number ? Should be 3 in your case.

**Comment by nathanielx** [comment] 2012-03-15 15:19
I am using Win 7 at work, unfortunately. I made the change and the output seems to confirm that it is loading 3 patters, here are the last few lines of the console:

```
app ready
pre session restore time: 0.286307
startup cache, total files: 98 cache hits: 98
startup time: 0.333672 (package setup was not run)
loaded 934 snippets
Package Control: Skipping automatic upgrade, last run at 2012-03-15 11:06:12, next run at 2012-03-15 12:06:12 or after
LOADED3
```

I was unable to get the time last night, but I'll try this on my Mac at home tonight, I'm curious if this is a platform related bug. :)

I'm not much of a python guy, but I'm more than willing to help debug. This plugin is exactly what I need!

**Comment by vojtajina** [comment] 2012-03-15 15:35
Cool, at least that means your config is correct. I guess your path has some special character that confuses the regexp parser. Could you do last thing ?

Change the block line 11 - 17 to this:

``` python
print current_file  # ADDED
        for pattern in view.settings().get('open_related_patterns', []):
            print pattern[0] # ADDED
            print pattern[1] # ADDED
            file = Converter(pattern[0], pattern[1]).convert(current_file)
            if file and os.path.exists(file):
                if win.num_groups() > 1:
                    win.focus_group((win.active_group() + 1) % win.num_groups())
                self.window.open_file(file)
                return
```

The only change = adding three print statements. And send me the output from console.
Then I should have all the data for reproducing it and fixing the bug.

Thank you so much, really appreciate your help. I need to add debugging :-D

**Comment by nathanielx** [comment] 2012-03-15 19:19
This is the return:

<pre>
print current_file  # ADDED
Writing file /C/Users/nate/AppData/Roaming/Sublime Text 2/Packages/Open Related/open_related.py with encoding UTF-8
Reloading plugin C:\Users\nate\AppData\Roaming\Sublime Text 2\Packages\Open Related\open_related.py
C:\Users\nate\Projects\export\functions\admin_open.pm
*/functions/*.pm
*/standard/css/*.css
*/functions/*.pm
*/standard/js/*.js
*/functions/*.pm
*/standard/templates/*.txt
</pre>


I think I see what you're getting at, so I did a rough hack on line 9 and added another print around line 16 to see the file it finds (if any):

<pre>
current_file = view.file_name().replace("\\", "/")
</pre>

 and now it opens 1, but not all three...

<pre>
Writing file /C/Users/nate/AppData/Roaming/Sublime Text 2/Packages/Open Related/open_related.py with encoding UTF-8
Reloading plugin C:\Users\nate\AppData\Roaming\Sublime Text 2\Packages\Open Related\open_related.py
C:/Users/nate/Projects/export/functions/admin_open.pm
*/functions/*.pm
*/standard/css/*.css
C:/Users/nate/Projects/export/standard/css/admin_open.css
</pre>


hope that helps!

**Comment by nathanielx** [comment] 2012-03-15 22:04
Actually, played a little more with it, and it works if I make the following changes:

<pre>
    def run(self):
        found_files = False;
        win = self.window
        view = win.active_view()
        current_file = view.file_name().replace("\\", "/")
        for pattern in view.settings().get('open_related_patterns', []):
            file = Converter(pattern[0], pattern[1]).convert(current_file)
            if file and os.path.exists(file):
                if win.num_groups() > 1:
                    win.focus_group((win.active_group() + 1) % win.num_groups())
                self.window.open_file(file)
                found_files = True;

        if not found_files:
            sublime.status_message("Cannot find related file !")
</pre>


But again, I'm not a python guy, so there might be better ways :)

**Comment by vojtajina** [comment] 2012-03-16 00:35
@natronx you are awesome !

The plugin was not supposed to open multiple files, but I think that's a valid feature, we can make it configurable (say `open_related.open_all` or something) and allow multiple patterns syntax like this:

```
"open_related_patterns":
[["*/functions/*.pm", "*/standard/css/*.css", "*/standard/js/*.js", "*/standard/templates/*.txt"]]
```

I created an issue for this feature #2

Back to the "windows" issue - yep, the problem is backslash. I hate windows :-D
I believe it would work even without any fix, but you would have to use backslashes in the pattern, in your case:

```
  "open_related_patterns":
     [
       ["*functions\\\\*.pm", "*standard\\\\css\\\\*.css"]
     ]
```

Anyway, I think normalizing windows path to forward slashes should not hurt anyone, as win can accept forward slashes as well. So I will merge this fix.

**Comment by nathanielx** [comment] 2012-03-16 03:32
Working in windows is not ideal, I'll check into escaping the config file first thing tomorrow!

Issue/feature #2 looks great, pattern grouping like that would be ideal! :)

Thanks for the help!

**Closed as completed** 2012-03-16 04:42 UTC

**Comment by vojtajina** [comment] 2012-03-16 04:49
@natronx Try to reboot Sublime, I pushed new version, that should fix your troubles with backslash in the path + allowing multiple files, check out readme.
